### ISSUE TITLE
Adicionar colunada validada na visita

### ISSUE THREAD

**Issue by roldaojr** [holocronifrn/siade-server#115]
Adicionar uma coluna para indicar se a visita foi validada pelo tablet (boolean validada) #87

**Comment by jefftb540** [comment]
Isso já tá feito

**Comment by roldaojr** [comment]
E como ficou o nome da coluna?

**Comment by jefftb540** [comment]
Acho que é imóvel_inspecionado

**Comment by roldaojr** [comment]
Achei que era, mas parece q não
