### ISSUE TITLE
na api mostrar apenas os bairros relacionados ao agente e incluir as colunas de sincronização

### ISSUE THREAD

**Issue by evangilo** [holocronifrn/siade-server#38]
Adicionar filtro "from" na busca de bairros e filtrar bairros pelo agente.

**Comment by roldaojr** [comment]
Atualmente o bairros estão sendo filtrados pelo município do agente.

**Comment by evangilo** [comment]
O ideal seria ser filtrado pelas quadras que o agente vai trabalhar.
