### ISSUE TITLE
Criar nova tela para distribuição de trabalho para agentes (Gerenciar Ciclo)

### ISSUE THREAD

**Issue by CristianoNunes** [holocronifrn/siade-server#39]
- Mudar a label "Alterar" na tela de Distribuir Trabalho para "Adicionar Área"

- Criar nova tela para a seleção de quadra. (Do jeito que está, quando tiver muitas quadras ficará dificil de selecionar).
DICA: Ao clicar no botão "Adicionar Área" deve se renderizar uma nova tela, onde o usuário deverá escolher o(s) bairro(s) que o agente irá trabalhar, e só assim a tela mostrará as quadras.

**Comment by roldaojr** [comment]
O botão não pode se chamar Adicionar por que ele também serve para remover

**Comment by roldaojr** [comment]
Sugestão e nova interface

![captura de tela 2015-02-24 17 21 19](https://cloud.githubusercontent.com/assets/2447787/6358830/4110666c-bc4d-11e4-93ca-6ce7c9c3c692.png)
