### ISSUE TITLE
Distribuir trabalhos - Colocar um campo para digitar as quadras que o agente irá trabalhar

### ISSUE THREAD

**Issue by jefftb540** [holocronifrn/siade-server#47]
Colocar um campo de texto onde o supervisor possa digitar as quadras que o agente irá trabalhar. Permitir a possibilidade de digitar intervalos. Ex: 1 - 15;17;20

**Comment by roldaojr** [comment]
Sugestão e nova interface

![captura de tela 2015-02-24 17 21 19](https://cloud.githubusercontent.com/assets/2447787/6358830/4110666c-bc4d-11e4-93ca-6ce7c9c3c692.png)

**Comment by roldaojr** [comment]
Relacionado a #39
