### ISSUE TITLE
Atualizar quantidade de imóveis na tela de distribuir trabalhos

### ISSUE THREAD

**Issue by jefftb540** [holocronifrn/siade-server#48]
Quando altera a quantidade de quadras que o agente está trabalhando, a quantidade de imóveis permanece a mesma

**Comment by roldaojr** [comment]
Não consegui reproduzir o bug. Aqui as quadras atualizam normal.

**Comment by luziana** [comment]
no meu também

**Comment by roldaojr** [comment]
Quando a mais de um ciclo cadastrado no sistema. O sistema faz a contagem dos imóveis errada.
