### ISSUE TITLE
Ordenar listagem de quadras

### ISSUE THREAD

**Issue by JefersonQueiroga** [holocronifrn/siade-server#6]
1º aprimoramento: Ordenar a listagem de quadras no detalhamento de bairro.
O ideal seria que as quadras esteja em ordem: quadra1, quadra2, quadra3 ...

2º aprimoramento : Colocar um botão para editar uma quadra no lugar do link.

**Comment by roldaojr** [comment]
Para o aprimoramento 1 basta trocar o tipo do atributo de CharField para PositiveIntegerField
