### ISSUE TITLE
Alterar tela de Distribuição de trabalho para agentes (Gerenciar Ciclo)

### ISSUE THREAD

**Issue by CristianoNunes** [holocronifrn/siade-server#64]
* Mudar a label de "Alterar" para "Distribuir Área".

* Mostrar quadras cadastradas, do jeito que está, o usuário não sabe que quadras estão cadastradas.

**Comment by roldaojr** [comment]
Distribuir Área não parece ser o nome mais adequado para esse botão

**Comment by roldaojr** [comment]
Foi criado uma nova tela para que o supervisor selecione as quadras do agente.
