### ISSUE TITLE
Tipo de imóvel: Terreno Baldio, não tem qtd de habitantes.

### ISSUE THREAD

**Issue by DemetriosCoutinho** [holocronifrn/siade-server#75]
![screenshot from 2015-03-01 23 05 15](https://cloud.githubusercontent.com/assets/10658627/6434429/74abcf70-c067-11e4-9115-7a14859316d9.png)

**Comment by DemetriosCoutinho** [comment]
Sem falar da mensagem em ingles

**Comment by roldaojr** [comment]
O ideal seria ocultar os campos habitantes, cães e gatos ao se selecionar a opção terreno baudio.
Porém uma solução mais simples é incluir na validação do formulário para que ao selecionar terreno baudio os valores desses campos devam ser sempre 0.
